# Generated by Django 5.0.4 on 2024-05-29 11:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=155)),
                ('photo', models.ImageField(blank=True, upload_to='photo')),
                ('specs', models.FileField(blank=True, upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=10)),
                ('flat_number', models.CharField(max_length=10)),
                ('default', models.BooleanField()),
                ('deleted', models.BooleanField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_address', to='utily.city')),
            ],
        ),
    ]
