# Generated by Django 5.0.4 on 2024-06-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utily', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flat_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
