# Generated by Django 5.0.4 on 2024-06-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utily', '0002_alter_address_flat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/photo'),
        ),
        migrations.AlterField(
            model_name='file',
            name='specs',
            field=models.FileField(blank=True, upload_to='media/files'),
        ),
    ]
