# Generated by Django 5.0.4 on 2024-06-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utily', '0003_alter_file_photo_alter_file_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
    ]
