# Generated by Django 5.0.4 on 2024-06-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utily', '0004_alter_file_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='specs',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
