# Generated by Django 5.0.4 on 2024-05-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(blank=True, default=12),
            preserve_default=False,
        ),
    ]
