# Generated by Django 5.0.4 on 2024-06-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userinfo_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='city',
        ),
    ]
