# Generated by Django 5.0.4 on 2024-06-03 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_useraddress_full_address_userinfo_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='born_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
