# Generated by Django 5.0.4 on 2024-06-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_gender_userinfo_age_alter_user_born_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
