# Generated by Django 5.0.4 on 2024-06-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_userinfo_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
