# Generated by Django 5.0.4 on 2024-06-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_userinfo_photo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='deleted',
            new_name='is_deleted',
        ),
    ]
