# Generated by Django 5.0.4 on 2024-05-29 11:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utily', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('about', models.TextField(max_length=300)),
                ('min_age', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField()),
                ('deleted', models.BooleanField()),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_event_photo_id', to='utily.file')),
            ],
        ),
        migrations.CreateModel(
            name='EventAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_address', models.CharField(max_length=100)),
                ('default', models.BooleanField()),
                ('deleted', models.BooleanField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address_address_event', to='utily.address')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_event_address', to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_visit', to='event.event')),
            ],
        ),
    ]
