# Generated by Django 5.0.4 on 2024-06-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Тренировки', 'Тренировки'), ('Игры', 'Игры')], default='Тренировки', max_length=20),
        ),
    ]
