# Generated by Django 5.0.4 on 2024-06-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Тренировки', 'Тренировка'), ('Игры', 'Игра')], default='Тренировки', max_length=20),
        ),
    ]
