# Generated by Django 5.0.4 on 2024-06-07 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteEvents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_favorite', to='event.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_favorite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
